package config

// DefaultTargetConfig default target config
const DefaultTargetConfig = `target:
  output_dir: ./tables
  # acronyms will be capitalized
  acronyms:
    - id
    - ip
    - uuid
  # tables included. priority is greater than exclude_tables
  include_tables:
    - ".*"
  # tables excluded
#  exclude_tables:
#    - ".*"
  # generate multiple files or one
  multiple_files: true
  template: |
    {{ $structName := CamelCase .Name }}
    // Code generated by reverse {{ Version }}. DO NOT EDIT.
    // date: {{ Date }}
    package {{ PackageName }}

    // {{ $structName }} {{ if .Comment }}{{ .Comment }}{{ else }}{{ .Name }}{{ end }}
    type {{ $structName }} struct {
        {{range $index, $column := .Columns -}}
        {{ CamelCase $column.Name }} {{ GoType $column.ColumnType }} ` + "`" + `json:"{{ $column.Name }}" gorm:"column:{{ $column.Name }}{{ if $column.IsPrimaryKey }};primaryKey{{ end }}"` + "`" + ` // {{ if $column.Comment }}{{ $column.Comment }}{{ else }}{{ $column.Name }}{{ end }}
        {{end -}}
    }

    // TableName {{ .Name }}
    func (t *{{ $structName }}) TableName() (string) {
      return "{{ .Name }}"
    }

`

// TargetConfig target config
type TargetConfig struct {
	OutputDir     string   `json:"output_dir" mapstructure:"output_dir"`
	Acronyms      []string `json:"acronyms" mapstructure:"acronyms"`
	ExcludeTables []string `json:"exclude_tables" mapstructure:"exclude_tables"`
	IncludeTables []string `json:"include_tables" mapstructure:"include_tables"`
	MultipleFiles bool     `json:"multiple_files" mapstructure:"multiple_files"`
	Template      string   `json:"template" mapstructure:"template"`
}

// InitTargetConfig load target config
func InitTargetConfig() (*TargetConfig, error) {
	c := &TargetConfig{}
	if err := config.ReadSection("target", c); err != nil {
		return nil, err
	}
	return c, nil
}
