package config

// DefaultTargetConfig default target config
const DefaultTargetConfig = `target:
  output_dir: ./tables
  # acronyms will be capitalized
  acronyms:
    - id
    - ip
    - uuid
  # tables included. priority is greater than exclude_tables
  include_tables:
    - ".*"
  # tables excluded
#  exclude_tables:
#    - ".*"
  # generate multiple files or one
  multiple_files: true
  template: |
    // Code generated by reverse {{ Version }}. DO NOT EDIT.
    // date: {{ Date }}

`

// TargetConfig target config
type TargetConfig struct {
	OutputDir     string   `json:"output_dir" mapstructure:"output_dir"`
	Acronyms      []string `json:"acronyms" mapstructure:"acronyms"`
	ExcludeTables []string `json:"exclude_tables" mapstructure:"exclude_tables"`
	IncludeTables []string `json:"include_tables" mapstructure:"include_tables"`
	MultipleFiles bool     `json:"multiple_files" mapstructure:"multiple_files"`
	Template      string   `json:"template" mapstructure:"template"`
}

// InitTargetConfig load target config
func InitTargetConfig() (*TargetConfig, error) {
	c := &TargetConfig{}
	if err := config.ReadSection("target", c); err != nil {
		return nil, err
	}
	return c, nil
}
